server:
  port: 8088
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: service1
            #uri: 'lb://service1'
            uri: 'lb://service1'
            predicates:
              - Path=/service1/**
            filters:
              - StripPrefix=1
          - id: service2
            #uri: 'lb://service2'
            uri: 'http://localhost:3333/'
            predicates:
              - Path=/service2/**
            filters:
              - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:1111/eureka/'